### ISSUE TITLE
Error: Cannot find module 'ejs'

### ISSUE THREAD

**Issue by busticated** [th0r/webpack-bundle-analyzer#7]
hey there -

i ran into the following error when i tried the run the analyzer:

    Error: Cannot find module 'ejs'
        at Function.Module._resolveFilename (module.js:325:15)
        at Function.Module._load (module.js:276:25)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at new View (/path/to/my/app/node_modules/express/lib/view.js:78:30)
        at EventEmitter.render (/path/to/my/app/node_modules/express/lib/application.js:569:12)
        at ServerResponse.render (/path/to/my/app/node_modules/express/lib/response.js:960:7)
        at /path/to/my/app/node_modules/webpack-bundle-analyzer/lib/viewer.js:44:9
        at Layer.handle [as handle_request] (/path/to/my/app/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/path/to/my/app/node_modules/express/lib/router/index.js:312:13)
        at /path/to/my/app/node_modules/express/lib/router/index.js:280:7
        at Function.process_params (/path/to/my/app/node_modules/express/lib/router/index.js:330:12)
        at next (/path/to/my/app/node_modules/express/lib/router/index.js:271:10)
        at SendStream.error (/path/to/my/app/node_modules/express/node_modules/serve-static/index.js:121:7)
        at emitOne (events.js:77:13)
        at SendStream.emit (events.js:169:7)

$node -v
`v4.6.0`

$npm -v
`2.15.11` (yeah, i know ;-)

$npm list --depth=0 

    ├── express@4.14.0
    ├── lodash@4.5.1
    ├── webpack@1.13.2
    ├── webpack-bundle-analyzer@1.3.0
    └── webpack-dev-middleware@1.6.1

the analyzer seems to have the deps it needs (edited for brevity):

    ├─┬ webpack-bundle-analyzer@1.3.0
    │ ├── acorn@4.0.3
    │ ├── chalk@1.1.3
    │ ├── commander@2.9.0
    │ ├── ejs@2.5.2
    │ ├── filesize@3.3.0
    │ ├── lodash@4.16.6
    │ └── opener@1.4.2

i get the same error whether i run as CLI or plugin.

**Comment by BrockWills** [comment]
I had the same problem but simply running npm install ejs fixed it for me. Strange that it doesn't seem to have installed even though it is a dependency.

**Comment by BrockWills** [comment]
Can confirm the npm version was the problem for me - after updating to latest npm version and reinstalling all my node_modules it worked fine.

**Comment by busticated** [comment]
yep, same result over here (after some coaxing :)

**Comment by 1silvertiger** [comment]
I have the same issue, but it doesn't work after updating npm and reinstalling ejs.

**Comment by valscion** [comment]
Please open a new issue with more details
